project:
  type: website
  output-dir: docs

website:
  description: "Adventures in STAT-334"
  title: "Data Science 2k26"
  site-url: "https://chmcfa23.github.io/DS334/"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/chmcfa23
format:
  html:
    theme:
      - minty
      - brand
    css: styles.css

editor: visual

